export const initialState = {
    user:null,
    token:null,
    allUsers:[],
    patients:[],
    doctors: [],
    msg:'',
    socket:{},
    clients:[],
    messages:[],
    allFriends:[],
    allRequests:[],
    audio:null,
    online:false,
    rejected_dr:[],
    approved_dr:[],
    admin_requests:[],
    groups:[],
    group_messages:[],
};
