export const initialState = {
    user:null,
    token:null,
    allUsers:[],
    patients:[],
    doctors: [],
    msg:'',
    socket:{},
    clients:[],
    messages:[],
    allFriends:[],
    allRequests:[],
    audio:null,
    online:false,
};
