//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrPatient_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedUser
    {
        public int Block_id { get; set; }
        public string BlockByPhone { get; set; }
        public string BlockUserPhone { get; set; }
    }
}
