//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrPatient_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCD
    {
        public int CCD_ID { get; set; }
        public string Patient_ID { get; set; }
        public string Doctor_ID { get; set; }
        public string CCD_Title { get; set; }
        public string CCD_Table { get; set; }
        public Nullable<System.DateTime> Visited_Date { get; set; }
    }
}
