//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrPatient_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int G_ID { get; set; }
        public string G_Name { get; set; }
        public string G_MemberIDs { get; set; }
        public string G_Created_By { get; set; }
        public Nullable<System.DateTime> G_Created_Date { get; set; }
        public string G_Image { get; set; }
    }
}
