//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrPatient_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int Invitaion_id { get; set; }
        public string FriendA_phone { get; set; }
        public string FriendB_phone { get; set; }
        public string Invitation_code { get; set; }
        public string Invitation_type { get; set; }
    }
}
