//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrPatient_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_ID { get; set; }
        public string From_ID { get; set; }
        public string To_ID { get; set; }
        public string Message_Content { get; set; }
        public string Message_Type { get; set; }
        public Nullable<bool> Is_Seen { get; set; }
        public string Created_Time { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Is_Group { get; set; }
    }
}
