//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrPatient_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferPatient
    {
        public string Patient_ID { get; set; }
        public string ReferFrom_ID { get; set; }
        public string ReferTo_ID { get; set; }
        public string AllowedFields { get; set; }
        public int Ref_ID { get; set; }
    }
}
